server:
  port: 8888
  contextPath: /glgg
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.111:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    hikari: #可配置项看这里 com.zaxxer.hikari.HikariConfig
      connectionTimeout: 30000 #等待连接池分配连接的最大时长（毫秒）
      maxLifetime: 28830000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放,参考MySQL wait_timeout，默认8小时
      maximumPoolSize: 15 #连接池中允许的最大连接数，缺省值：10 connections = ((core_count * 2) + effective_spindle_count)
      idleTimeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
  redis:
    host: 192.168.1.111
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-wait: -1
      max-active: 8

    
      
mybatis:
  mapperLocations: classpath:mapper/*.xml